spring.application.name=ai-assistant-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/pass_ai_assistant
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=change_this_to_a_long_random_string_at_least_32_characters_long
app.jwt.expiration=86400000
server.port=8081